### ISSUE TITLE
match case syntax error at start

### ISSUE THREAD

**Issue by dl5dla** [irimitenkan/CO2MqttSensor#2]
I installed the package on a Raspberry PI 2B (raspbian buster, Python 3.7.3).

When starting with 
  $ python3 co2sensor.py

I get the following error message:

Traceback (most recent call last):
  File "co2sensor.py", line 20, in <module>
    from co2sensorclient import startClient
  File "/home/jonas/CO2MqttSensor/co2sensorclient.py", line 8, in <module>
    import MQTTClient as hass
  File "/home/jonas/CO2MqttSensor/MQTTClient.py", line 229
    match rc:
           ^
SyntaxError: invalid syntax

Any idea how to solve that?

Thanks a lot.
Regards,
 Peter

**Comment by irimitenkan** [comment]
match/case needs Python 3.10 or newer, which is not supported with Debian buster.
Hence you have to upgrade to bookworm release which actually supports Python 3.11.

**Comment by dl5dla** [comment]
Thank you. Upgrade to bookworm solved that problem :-)
