### ISSUE TITLE
waiting for dict_keys([]) values from device

### ISSUE THREAD

**Issue by dl5dla** [irimitenkan/CO2MqttSensor#3]
After successful install, I got the following error (?) messages when starting from command line ($ python3 co2sensor.py):

09:30:54 - DEBUG - try to open vendor 0x4d9 - product 0xa052
09:30:54 - DEBUG - CO2 devices opened: Manufacturer = Holtek , Product = USB-zyTemp
09:30:54 - DEBUG - enter output mode - send_feature_report: 2
09:30:54 - DEBUG - Humidity sensor not supported by and removed
09:30:54 - DEBUG - SW activated sensors due to HW=AIRCO2NTROL_MINI : dict_keys(['CO2', 'Temperature'])
09:30:54 - DEBUG - ----> waiting for dict_keys([]) values froom device
09:30:54 - DEBUG - unsed sensor item 0x28=42163 (value)
09:30:54 - DEBUG - unsed sensor item 0xb0=42026 (value)
09:30:54 - DEBUG - unsed sensor item 0xdb=42042 (value)
09:30:54 - DEBUG - unsed sensor item 0xdd=42034 (value)
09:30:56 - DEBUG - unsed sensor item 0x1e=42122 (value)
09:30:57 - DEBUG - unsed sensor item 0x47=42133 (value)
09:30:57 - DEBUG - unsed sensor item 0xf=42154 (value)
09:30:57 - DEBUG - unsed sensor item 0xd5=42146 (value)

**Comment by irimitenkan** [comment]
Hi Peter,

these messages are just debug messages, but I guess this output never stops on your rpi and does not look like this:

```
13:02:46 - DEBUG - try to open vendor 0x4d9 - product 0xa052
13:02:47 - DEBUG - CO2 devices opened: Manufacturer = Holtek , Product = USB-zyTemp
13:02:47 - DEBUG - enter output mode - send_feature_report: 2
13:02:47 - DEBUG - Humidity sensor not supported by and removed
13:02:47 - DEBUG - SW activated sensors due to HW=AIRCO2NTROL_MINI : dict_keys(['CO2', 'Temperature'])
13:02:47 - DEBUG - ----> waiting for dict_keys([]) values froom device
13:02:48 - DEBUG - unsed sensor item 0x6d=2965 (value)
13:02:48 - DEBUG - unsed sensor item 0x6e=10227 (value)
13:02:48 - DEBUG - unsed sensor item 0x71=1259 (value)
13:02:48 - DEBUG - CO2 = 1227 ppm
13:02:49 - DEBUG - unsed sensor item 0x4f=8403 (value)
13:02:49 - DEBUG - unsed sensor item 0x52=10254 (value)
13:02:51 - DEBUG - unsed sensor item 0x41=0 (value)
13:02:51 - DEBUG - unsed sensor item 0x43=2640 (value)
13:02:51 - DEBUG - Temperature = 18.66 °C
13:02:51 - DEBUG - <--- received values froom device
13:02:51 - DEBUG - ----> waiting for dict_keys(['CO2', 'Temperature']) values froom device
13:02:53 - DEBUG - unsed sensor item 0x6d=2965 (value)
13:02:53 - DEBUG - unsed sensor item 0x6e=10227 (value)
13:02:53 - DEBUG - unsed sensor item 0x71=1259 (value)
13:02:53 - DEBUG - CO2 = 1227 ppm
13:02:54 - DEBUG - unsed sensor item 0x57=7308 (value)
13:02:54 - DEBUG - unsed sensor item 0x56=10274 (value)
13:02:56 - DEBUG - unsed sensor item 0x41=0 (value)
13:02:56 - DEBUG - unsed sensor item 0x43=2637 (value)
13:02:56 - DEBUG - Temperature = 18.66 °C


```
The "error" is, that your device never sends the item ids:
eHum1 = 0x41
eTemp = 0x42
eHum2 = 0x44
eCO2 = 0x50
eCO2_2 = 0x71 

Strange, I have no idea what is the root cause, so let us check the correct access rights, please try:

```
irimi@mrpi:~/CO2MqttSensor $ lsusb
Bus 001 Device 002: ID 04d9:a052 Holtek Semiconductor, Inc. USB-zyTemp
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```
and check correct group "plugdev" is set for Bus 001 Device 002 , here the ouput of my Raspberry Pi Zero 2 W:

```
irimi@mrpi:~/CO2MqttSensor $ ls -la /dev/bus/usb/001/002
crw-rw---- 1 root plugdev 189, 1 Dec  4 18:32 /dev/bus/usb/001/002

```

**Comment by dl5dla** [comment]
Hi,
here are my output lines for the both commands. They are looking quite the same.
--------
root@wohnzimmerPI:/etc/init.d# lsusb
Bus 001 Device 006: ID 04d9:a052 Holtek Semiconductor, Inc. USB-zyTemp
Bus 001 Device 005: ID 0451:16c8 Texas Instruments, Inc. CC2538 USB CDC
Bus 001 Device 004: ID 239a:800c Adafruit Feather 32u4
Bus 001 Device 003: ID 0424:ec00 Microchip Technology, Inc. (formerly SMSC) SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Microchip Technology, Inc. (formerly SMSC) SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
-------
root@wohnzimmerPI:/etc/init.d# ls -la /dev/bus/usb/001/002
crw-rw-r-- 1 root root 189, 1 Dec  4 18:32 /dev/bus/usb/001/002
-------
For test, I added some debug outputs in the file co2device.py, near line 145 and printed the values rec[0] ... rec[7], but I could not find the 0x42 or 0x50 in the output, so I guess the read input is already somehow wrong.
Interesting might be that the software "minimon" (https://sourceforge.net/projects/minimon/) delivers correct temperature and co2 values, but my python knowledge is close to zero, so I had no chance to compare both codes.

**Comment by dl5dla** [comment]
Hi,
here are my output lines for the both commands. They are looking quite the same.

root@wohnzimmerPI:/etc/init.d# lsusb
Bus 001 Device 006: ID 04d9:a052 Holtek Semiconductor, Inc. USB-zyTemp
Bus 001 Device 005: ID 0451:16c8 Texas Instruments, Inc. CC2538 USB CDC
Bus 001 Device 004: ID 239a:800c Adafruit Feather 32u4
Bus 001 Device 003: ID 0424:ec00 Microchip Technology, Inc. (formerly SMSC) SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Microchip Technology, Inc. (formerly SMSC) SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

root@wohnzimmerPI:/etc/init.d# ls -la /dev/bus/usb/001/002
crw-rw-r-- 1 root root 189, 1 Dec  4 18:32 /dev/bus/usb/001/002

For test, I added some debug outputs in the file co2device.py, near line 145 and printed the values rec[0] ... rec[7], but I could not find the 0x42 or 0x50 in the output, so I guess the read input is already somehow wrong.
Interesting might be that the software "minimon" (https://sourceforge.net/projects/minimon/) delivers correct temperature and co2 values, but my python knowledge is close to zero, so I had no chance to compare both codes.

**Comment by irimitenkan** [comment]
As I can see you are running the script as root, but that is not a good idea. Please try to execute the script as non root user e.g. the user which was configured when you set up your bookworm installation. I don't know, but it might be possible that there are some root user restrictions of the hid python library which is used to access the CO2 device via USB.

Before execution don't forget to setup correct udev rules , see [here](https://github.com/irimitenkan/CO2MqttSensor#udev-rules), the 1st entry with group = "plugdev" and check the output of  
`ls -la /dev/bus/usb/001/002`  shows the assignment to `plugdev`.

For automatic script execution I recommend to setup a user service , see [here](https://github.com/irimitenkan/CO2MqttSensor#running) .

**Comment by dl5dla** [comment]
Thanks. 
I tried running 'python3 co2sensor.py' as normal user and as root. The behaviour is the same.

ls -la /dev/bus/usb/001/006 delivers
"crw-rw---- 1 root plugdev 189, 5  5. Dez 22:53 /dev/bus/usb/001/006"
(my co2 device is at Bus 001 Device 006)

**Comment by dl5dla** [comment]
I assume, that the issue is related to a missing decrypt function. As far as I understood older CO2 devices encrypt the messages while newer do not.  Other scripts like "minimon" (see link above) test the fourth byte against "0x0d". If not exists, decryption is applied to the received eight bytes.

My device is from 2016, so may be one of the older versions.

**Comment by irimitenkan** [comment]
> I assume, that the issue is related to a missing decrypt function. As far as I understood older CO2 devices encrypt the messages while newer do not. Other scripts like "minimon" (see link above) test the fourth byte against "0x0d". If not exists, decryption is applied to the received eight bytes.
> 
> My device is from 2016, so may be one of the older versions.

Ah, ok, thank you for that information, I was not aware of older models with encrypted messages. My own device is quite new. To fix it I'll will add the decrypt function .

**Comment by dl5dla** [comment]
Perfect - looking forward  to a next version:-)
Thank you

**Comment by irimitenkan** [comment]
@dl5dla: I tried to add decrypt support , please see updated branch "next". But I was not able to test & verify the code since I don't have a device which encrypts the data. Feedback is welcome :smiley: .

**Comment by dl5dla** [comment]
Yes, the new version is working! The temperature and co2 values are now sent via MQTT. See the debug output below. Thank you very much for the quick solution!

EDIT: would it be possible a make the MQTT topic (at least the main topic) configurable?  I would like to have all topics related to homeassistant starting with "homeassistant/...".

23:11:03 - DEBUG - try to open vendor 0x4d9 - product 0xa052
23:11:03 - DEBUG - CO2 devices opened: Manufacturer = Holtek , Product = USB-zyTemp
23:11:03 - DEBUG - enter output mode - send_feature_report: 9
23:11:03 - DEBUG - Humidity sensor not supported by and removed
23:11:03 - DEBUG - SW activated sensors due to HW=AIRCO2NTROL_MINI : dict_keys(['CO2', 'Temperature'])
23:11:03 - DEBUG - ----> waiting for dict_keys([]) values froom device
23:11:03 - DEBUG - decrypting
23:11:03 - DEBUG - 1:ignoring sensor item 0xe3=34922 (value)
23:11:05 - DEBUG - decrypting
23:11:05 - DEBUG - 2:ignoring sensor item 0x6d=911 (value)
23:11:05 - DEBUG - decrypting
23:11:05 - DEBUG - 3:ignoring sensor item 0x6e=25274 (value)
23:11:05 - DEBUG - decrypting
23:11:05 - DEBUG - 4:ignoring sensor item 0x71=1317 (value)
23:11:05 - DEBUG - decrypting
23:11:05 - DEBUG - CO2 = 1277 ppm
23:11:06 - DEBUG - decrypting
23:11:06 - DEBUG - 6:ignoring sensor item 0x4f=8774 (value)
23:11:06 - DEBUG - decrypting
23:11:06 - DEBUG - 7:ignoring sensor item 0x52=10181 (value)
23:11:07 - DEBUG - decrypting
23:11:07 - DEBUG - 8:ignoring sensor item 0x41=0 (value)
23:11:08 - DEBUG - decrypting
23:11:08 - DEBUG - 9:ignoring sensor item 0x43=3168 (value)
23:11:08 - DEBUG - decrypting
23:11:08 - DEBUG - Temperature = 23.35 °C

**Comment by irimitenkan** [comment]
> Yes, the new version is working! The temperature and co2 values are now sent via MQTT. See the debug output below. Thank you very much for the quick solution!

Great, then I can release the changes ! Thank you for helping me to improve the device integration.

> EDIT: would it be possible a make the MQTT topic (at least the main topic) configurable? I would like to have all topics related to homeassistant starting with "homeassistant/...".

You don't like the hostname as part of the node id ? I used this to have a unique identifier if more than one single CO2 sensor is available.
As quick workaround you can change the code in MQTTClient.py , line 172:

```
    def _getHostTopicId(self):
        """
        defines the node_id in hass discovery topic
        """
        return socket.gethostname()

```
Just change it to `return "what_do_you_like" `, but keep in mind that homeassistant's discovery prefix is "homeassistant", too.

EDIT: or do you want to change the client id  ? It is actually defined in co2sensorclient.py `MQTT_CLIENT_ID = 'co2sensor'` you can change it e.g. to `homeassistant/co2sensor`

**Comment by dl5dla** [comment]
Thanks. As proposed I changed the MQTT_CLIENT_ID accordingly. I guess that's what I want.

BTW, I recognized, that after a runtime of about 15 hours I got the error:
14:56:32 - ERROR - unexpected values from device, missing CO2/T/H value items
14:56:32 - ERROR - co2sensor: polling has failed
14:56:32 - INFO - MQTT client co2sensor down
No idea what the reason was and whether I should increase the parameter LOOP_ERROR hoping that values will be read again after some time. In any case the process shouldn't stop and keep running.

**Comment by irimitenkan** [comment]
> BTW, I recognized, that after a runtime of about 15 hours I got the error:
> 14:56:32 - ERROR - unexpected values from device, missing CO2/T/H value items
> 14:56:32 - ERROR - co2sensor: polling has failed
> 14:56:32 - INFO - MQTT client co2sensor down

Mmh, I added a loop break,  to avoid an endless loop without error if the device never sends CO2 and T values .  Maybe the error threshold is too low ? Please try to increase `LOOP_ERROR` in co2device.py , line 11, to higher value, e.g. 30.

**Comment by dl5dla** [comment]
Just for info: After changing LOOP_ERROR to 30, the process is running now since a week.
Thanks again.
